# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('desc', models.CharField(max_length=300, verbose_name='描述')),
                ('lost_location', models.CharField(max_length=100, verbose_name='走失地点')),
                ('lost_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='走失日期')),
                ('img', models.ImageField(upload_to='public_welfare/lost/%Y/%m', verbose_name='照片')),
                ('weibo', models.URLField(max_length=100, verbose_name='微博地址')),
                ('closed', models.BooleanField(verbose_name='是否结案')),
                ('closed_explain', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='结案详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '走失儿童',
                'verbose_name_plural': '走失儿童',
            },
        ),
    ]
