# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 23:30
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='相册名')),
                ('desc', models.CharField(max_length=100, verbose_name='文章描述')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章详细信息')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('is_top', models.IntegerField(choices=[(0, '未置顶'), (1, '已置顶')], default=0, verbose_name='是否置顶')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
