# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='文章名')),
                ('desc', models.CharField(max_length=100, verbose_name='文章描述')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
                ('content', models.TextField(verbose_name='文章详细信息')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('is_top', models.IntegerField(choices=[(0, '未置顶'), (1, '已置顶')], default=0, verbose_name='是否置顶')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
