# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_banner_recommend_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='href',
            field=models.URLField(blank=True, null=True, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='主题描述'),
        ),
    ]
