# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 19:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_auto_20181015_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article', verbose_name='文章')),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Recommend', verbose_name='编辑推荐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '编辑推荐详情',
                'verbose_name_plural': '编辑推荐详情',
            },
        ),
        migrations.CreateModel(
            name='TopicDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article', verbose_name='文章')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Topic', verbose_name='主题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '主题详情',
                'verbose_name_plural': '主题详情',
            },
        ),
    ]
