# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='audiodetail',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Audio', verbose_name='电台'),
        ),
        migrations.AddField(
            model_name='audiodetail',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='audiodetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='audio',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer', verbose_name='歌手'),
        ),
        migrations.AddField(
            model_name='audio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album', verbose_name='专辑'),
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer', verbose_name='歌手'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AlterUniqueTogether(
            name='audiodetail',
            unique_together=set([('audio', 'song')]),
        ),
        migrations.AlterUniqueTogether(
            name='albumdetail',
            unique_together=set([('album', 'song')]),
        ),
    ]
