# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180809_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album', verbose_name='专辑')),
            ],
            options={
                'verbose_name': '专辑详情页',
                'verbose_name_plural': '专辑详情页',
            },
        ),
        migrations.CreateModel(
            name='AudioListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AudioList', verbose_name='电台')),
            ],
            options={
                'verbose_name': '电台详情页',
                'verbose_name_plural': '电台详情页',
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.AddField(
            model_name='audiolistdetail',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲'),
        ),
        migrations.AlterUniqueTogether(
            name='audiolistdetail',
            unique_together=set([('audio', 'song')]),
        ),
        migrations.AlterUniqueTogether(
            name='albumdetail',
            unique_together=set([('album', 'song')]),
        ),
    ]
