# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180809_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '电台详情页',
                'verbose_name_plural': '电台详情页',
            },
        ),
        migrations.RenameModel(
            old_name='AudioList',
            new_name='Audio',
        ),
        migrations.AlterUniqueTogether(
            name='audiolistdetail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='audiolistdetail',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audiolistdetail',
            name='song',
        ),
        migrations.AlterField(
            model_name='albumdetail',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album', verbose_name='专辑'),
        ),
        migrations.DeleteModel(
            name='AudioListDetail',
        ),
        migrations.AddField(
            model_name='audiodetail',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Audio', verbose_name='电台'),
        ),
        migrations.AddField(
            model_name='audiodetail',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='歌曲'),
        ),
        migrations.AlterUniqueTogether(
            name='audiodetail',
            unique_together=set([('audio', 'song')]),
        ),
    ]
