# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='封面')),
                ('order', models.IntegerField(default=10, help_text='排序字段', verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to='avatar/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '简介',
                'verbose_name_plural': '简介',
            },
        ),
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('type', models.CharField(choices=[('profile', '个人资料'), ('contact', '联系方式')], help_text='类型', max_length=8, verbose_name='类型')),
                ('image', models.ImageField(upload_to='content/%Y/%m', verbose_name='封面')),
                ('order', models.IntegerField(default=10, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式',
                'proxy': True,
                'indexes': [],
            },
            bases=('mp.profiledetail',),
        ),
    ]
