# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '简介', 'verbose_name_plural': '简介'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='user',
        ),
    ]
