# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_auto_20180808_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='order',
            field=models.IntegerField(default=10, verbose_name='排序'),
        ),
    ]
