# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_profiledetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='type',
            field=models.CharField(choices=[('profile', '个人资料'), ('contact', '联系方式')], max_length=8, verbose_name='类型'),
        ),
    ]
