# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0004_auto_20180808_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=10, help_text='排序字段', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='profiledetail',
            name='type',
            field=models.CharField(choices=[('profile', '个人资料'), ('contact', '联系方式')], help_text='类型', max_length=8, verbose_name='类型'),
        ),
    ]
