# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='视频名称')),
                ('desc', models.CharField(max_length=100, verbose_name='视频描述')),
                ('file', models.FileField(upload_to='video/%Y/%m', verbose_name='视频文件')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='视频日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='视频合集名')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '视频合集',
                'verbose_name_plural': '视频合集',
            },
        ),
        migrations.CreateModel(
            name='VideoCollectionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='视频')),
                ('video_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.VideoCollection', verbose_name='视频合集')),
            ],
            options={
                'verbose_name': '视频合集明细',
                'verbose_name_plural': '视频合集明细',
            },
        ),
        migrations.AlterUniqueTogether(
            name='videocollectiondetail',
            unique_together=set([('video_collection', 'video')]),
        ),
    ]
