# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='视频名称'),
        ),
        migrations.AlterField(
            model_name='videocollection',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='视频合集名'),
        ),
        migrations.AlterUniqueTogether(
            name='videocollectiondetail',
            unique_together=set([('video_collection', 'video')]),
        ),
    ]
