# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppIntro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('image', models.ImageField(upload_to='app/intro/%Y/%m', verbose_name='封面')),
                ('type', models.CharField(choices=[('intro', '引导页'), ('startup', '启动页')], default='intro', help_text='类型', max_length=10, verbose_name='类型')),
                ('link', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('order', models.IntegerField(default=10, help_text='排序字段', verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_del', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'App引导页',
                'verbose_name_plural': 'App引导页',
            },
        ),
        migrations.CreateModel(
            name='AppStartUpPage',
            fields=[
            ],
            options={
                'verbose_name': 'App启动页',
                'verbose_name_plural': 'App启动页',
                'proxy': True,
                'indexes': [],
            },
            bases=('appintro.appintro',),
        ),
    ]
