# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_gallerydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='相册名'),
        ),
        migrations.AlterField(
            model_name='gallerydetail',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Gallery', verbose_name='相册'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='照片名称'),
        ),
        migrations.AlterUniqueTogether(
            name='gallerydetail',
            unique_together=set([('gallery', 'photo')]),
        ),
    ]
