# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20181009_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='photo/%Y/%m', verbose_name='照片文件'),
        ),
    ]
